title: doublylinked
description: "List of my tech notes on security-devopsy topics."
author: xvirgov
github_username: xvirgov
url: "https://doublylinked.com"
baseurl: ""

# Theme — Minima, GitHub Pages' natively supported default
theme: minima

# Plugins (allowed on GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalink format: /YYYY/MM/post-title/
permalink: /:year/:month/:title/

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
